

const data = [
  //new datas
  {
    ProductName:"shirt",
    Brand:"carval",
    color:"green",
    Quantity:"45",
    Category:"Men",
    Type:"Lower",
    size:"XL",
    Description:"good product",
    Price:"3000",
    URL:"https://rukminim1.flixcart.com/image/612/612/xif0q/shopsy-ethnic-set/r/c/t/xxl-1-maa-collection-original-imagmcn2ezkvkkxf.jpeg?q=70",
  },
  {
    ProductName:"shirt",
    Brand:"carval",
    color:"blue",
    Quantity:"45",
    Category:"Men",
    Type:"Lower",
    size:"XL",
    Description:"good product",
    Price:"3000",
    URL:"https://rukminim1.flixcart.com/image/612/612/xif0q/shopsy-ethnic-set/r/c/t/xxl-1-maa-collection-original-imagmcn2ezkvkkxf.jpeg?q=70",
  },
  {
    ProductName:"shirt",
    Brand:"carval",
    color:"red",
    Quantity:"45",
    Category:"Men",
    Type:"Lower",
    size:"XL",
    Description:"good product",
    Price:"3000",
    URL:"https://rukminim1.flixcart.com/image/612/612/xif0q/shopsy-ethnic-set/r/c/t/xxl-1-maa-collection-original-imagmcn2ezkvkkxf.jpeg?q=70",
  },
  {
    ProductName:"shirt",
    Brand:"carval",
    color:"green",
    Quantity:"45",
    Category:"Men",
    Type:"Lower",
    size:"XL",
    Description:"good product",
    Price:"3000",
    URL:"https://rukminim1.flixcart.com/image/612/612/xif0q/shopsy-ethnic-set/r/c/t/xxl-1-maa-collection-original-imagmcn2ezkvkkxf.jpeg?q=70",
  },
  {
    ProductName:"shirt",
    Brand:"carval",
    color:"blue",
    Quantity:"45",
    Category:"Woman",
    Type:"Lower",
    size:"XL",
    Description:"good product",
    Price:"3000",
    URL:"https://rukminim1.flixcart.com/image/612/612/xif0q/shopsy-ethnic-set/r/c/t/xxl-1-maa-collection-original-imagmcn2ezkvkkxf.jpeg?q=70",
  },
  {
    ProductName:"shirt",
    Brand:"carval",
    color:"red",
    Quantity:"45",
    Category:"Woman",
    Type:"Lower",
    size:"XL",
    Description:"good product",
    Price:"3000",
    URL:"https://rukminim1.flixcart.com/image/612/612/xif0q/shopsy-ethnic-set/r/c/t/xxl-1-maa-collection-original-imagmcn2ezkvkkxf.jpeg?q=70",
  },
  {
    ProductName:"shirt",
    Brand:"carval",
    color:"green",
    Quantity:"45",
    Category:"Men",
    Type:"Lower",
    size:"XL",
    Description:"good product",
    Price:"3000",
    URL:"https://rukminim1.flixcart.com/image/612/612/xif0q/shopsy-ethnic-set/r/c/t/xxl-1-maa-collection-original-imagmcn2ezkvkkxf.jpeg?q=70",
  },
  {
    ProductName:"shirt",
    Brand:"carval",
    color:"green",
    Quantity:"45",
    Category:"Men",
    Type:"Lower",
    size:"XL",
    Description:"good product",
    Price:"3000",
    URL:"https://rukminim1.flixcart.com/image/612/612/xif0q/shopsy-ethnic-set/r/c/t/xxl-1-maa-collection-original-imagmcn2ezkvkkxf.jpeg?q=70",
  },
  {
    ProductName:"shirt",
    Brand:"carval",
    color:"green",
    Quantity:"45",
    Category:"Men",
    Type:"Lower",
    size:"XL",
    Description:"good product",
    Price:"3000",
    URL:"https://rukminim1.flixcart.com/image/612/612/xif0q/shopsy-ethnic-set/r/c/t/xxl-1-maa-collection-original-imagmcn2ezkvkkxf.jpeg?q=70",
  },
  {
    ProductName:"shirt",
    Brand:"carval",
    color:"green",
    Quantity:"45",
    Category:"Men",
    Type:"Lower",
    size:"XL",
    Description:"good product",
    Price:"3000",
    URL:"https://rukminim1.flixcart.com/image/612/612/xif0q/shopsy-ethnic-set/r/c/t/xxl-1-maa-collection-original-imagmcn2ezkvkkxf.jpeg?q=70",
  },
  {
    ProductName:"shirt",
    Brand:"carval",
    color:"green",
    Quantity:"45",
    Category:"Men",
    Type:"Lower",
    size:"XL",
    Description:"good product",
    Price:"3000",
    URL:"https://rukminim1.flixcart.com/image/612/612/xif0q/shopsy-ethnic-set/r/c/t/xxl-1-maa-collection-original-imagmcn2ezkvkkxf.jpeg?q=70",
  },
  {
    ProductName:"shirt",
    Brand:"carval",
    color:"green",
    Quantity:"45",
    Category:"Men",
    Type:"Lower",
    size:"XL",
    Description:"good product",
    Price:"3000",
    URL:"https://rukminim1.flixcart.com/image/612/612/xif0q/shopsy-ethnic-set/r/c/t/xxl-1-maa-collection-original-imagmcn2ezkvkkxf.jpeg?q=70",
  },
  {
    ProductName:"shirt",
    Brand:"carval",
    color:"green",
    Quantity:"45",
    Category:"Men",
    Type:"Lower",
    size:"XL",
    Description:"good product",
    Price:"3000",
    URL:"https://rukminim1.flixcart.com/image/612/612/xif0q/shopsy-ethnic-set/r/c/t/xxl-1-maa-collection-original-imagmcn2ezkvkkxf.jpeg?q=70",
  },
  {
    ProductName:"shirt",
    Brand:"carval",
    color:"green",
    Quantity:"45",
    Category:"Men",
    Type:"Lower",
    size:"XL",
    Description:"good product",
    Price:"3000",
    URL:"https://rukminim1.flixcart.com/image/612/612/xif0q/shopsy-ethnic-set/r/c/t/xxl-1-maa-collection-original-imagmcn2ezkvkkxf.jpeg?q=70",
  },
  {
    ProductName:"shirt",
    Brand:"carval",
    color:"green",
    Quantity:"45",
    Category:"Men",
    Type:"Lower",
    size:"XL",
    Description:"good product",
    Price:"3000",
    URL:"https://rukminim1.flixcart.com/image/612/612/xif0q/shopsy-ethnic-set/r/c/t/xxl-1-maa-collection-original-imagmcn2ezkvkkxf.jpeg?q=70",
  },
 

];

export default data;
